[package]
name = "minecraft-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = "0.14.0"
nalgebra-glm = "0.18.0"
sfml = "0.21.0"
lazy_static = "1.4.0"
rand = "0.9.0-alpha.1"
rand_core = "0.9.0-alpha.1"
rand_pcg = "0.9.0-alpha.1"
gl_loader = "0.1.2"
